### ISSUE TITLE
Audio glitch on some devices (sample rate specific)

### ISSUE THREAD

**Issue by rpattabi** [libpd/libpd#245]
I reported https://github.com/libpd/pd-for-android/issues/89. I suspect, this is more of a libpd issue.

This issue is reproducible with PdTest in the samples. It affects wide range of devices such as Xiaomi Marshmallow and newer (case 1), Samsung Oreo (case 2) devices.

**Comment by danomatika** [comment]
Yup. It's a general problem related to Pd's fixed block size not aligning well along some sample rate boundaries. We've done some work towards this for iOS (#177 #212 #225 #228) but what I think is really needed is built-in sample rate conversion. I'm thinking it could best be done as an optional processing layer.

**Comment by rpattabi** [comment]
Fixed block size of 64 may be one of the issues. However, we have two scenarios where blocksize alignment with samplerate doesn't explain the glitch:

 1. Samplerate of 44100, which **is not** integer multiple of 64, works without glitches on most devices except the one mentioned.
 2. Samplerate of 48000, which **is** integer multiple of 64, causes glitch on specific devices. On those devices 44100 works flawlessly.

Also we have verified that the glitch is not due to lack of processing power. Playing simple sine waves is enough to reproduce the issue of these cases.

**Comment by danomatika** [comment]
I believe the issue comes up when you want to work with 44100 but the device *only* gives you 48000. This is the case for newer iOS devices without audio jack, ie. iPhone 6S, etc.

**Comment by rpattabi** [comment]
On Android, 44100 is always supported. As I mentioned, this is the issue only with libpd. If we use an alternative (we tested with [oboe](https://github.com/google/oboe)), there is no issue irrespective of the samplerate.

**Comment by cerupcat** [comment]
@rpattabi did you ever find a solution? I'm seeing audio glitching, but only when writing audio to a file.

**Comment by rpattabi** [comment]
@cerupcat I haven't found a solution. :-/ You could try a different samplerate (44.1k or 48k) specific for the problematic device.

**Comment by danomatika** [comment]
Only solution is to add sample rate conversion which I have not had the time to do.

**Comment by rpattabi** [comment]
@danomatika I'm not sure that adding sample rate conversion would help here. Reasons:

* android does samplerate conversion internally, yet we see this glitch on these devices.
* We see the glitch even when there is no need for samplerate conversion, i.e., when playing at device native sample rate of 48khz on Samsung Galaxy A5, A7, J7, Nokia 6 and Xiaomi devices.
* More importantly, **playback is glitchy only when we have opted for input channel. If we disable input channel, playback is not glitchy** even on problematic devices **at any sample rate**.

**Comment by danomatika** [comment]
Ok then good luck. I have no experience with Android development, pinging @nettoyeurny.

**Comment by danomatika** [comment]
>android does samplerate conversion internally

That was what I thought about iOS but this is no longer the case with the newer devices and AudioUnits, hence my initial take.

**Comment by danomatika** [comment]
>More importantly, playback is glitchy only when we have opted for input channel. If we disable input channel, playback is not glitchy even on problematic devices at any sample rate.

Does changing the number of inputs have an effect? It could simply be a channel mismatch as in, libpd is copying the sample buffer with the wrong offset, etc.

**Comment by rpattabi** [comment]
> Does changing the number of inputs have an effect?

We haven't checked this. Always checked with zero or one input channel. We'll try and let you know.

Please note that even when we just output a simple sine wave **without processing or routing input audio in any way**, we have glitch on these devices on these sample rates.

To get glitch, only thing we did is to set 1 as the number of input channels in pd-for-android/libpd (`initAudio`/`openAudio`). As mentioned, **same sine wave output** is not glitchy when number of input channels is set to 0.

**Comment by danomatika** [comment]
As this is an Android problem, you should probably look into the opensl_stream backend which is used by libpd on Android: https://github.com/nettoyeurny/opensl_stream/tree/5f3930698569754c519f5b3e4cc7691223bc99a8

**Comment by rpattabi** [comment]
Thanks for pointing out this code. This is interesting from ReadMe

> **Known issues**
>
>  - At 48000Hz, Galaxy Nexus and Nexus 10 produce glitchy output.
>  - At 44100Hz, Galaxy Nexus tends to glitch when switching activities or bringing up large dialogs.
>  - Touch sounds occasionally cause OpenSL to glitch. It's probably a good idea to disable touch sounds in audio apps.
>
> These problems are not specific to opensl_stream and have been reproduced in other settings.

**Comment by cerupcat** [comment]
I moved to opensl_stream and things are better, but I still have various issues here and there on certain devices - especially when trying to play background audio.

I'm curious if anyone has tried using https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform. I don't know if these issues are PD related, Andoird related or what.

**Comment by rpattabi** [comment]
> I don't know if these issues are PD related, Andoird related or what.

These issues are pd-for-android (or libpd) related, as I mentioned oboe works fine on any sample rate.

> I moved to opensl_stream and things are better

I thought by default opensl stream is used. What change did you do?

> I also had to set sample rate to 44.1k independent of device, otherwise I get issues

Please be aware, on some devices 44.1k causes glitch. Could you point out which devices you found with 44.1k working better instead of device sample rate?

> I'm curious if anyone has tried using https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform

Aware of it, but not tried. However, I think the license needs to be looked at closely for suitability.

**Comment by fomalsd** [comment]
Are there any news about built-in sample rate conversion and details on how it could be implemented?
Looks like all iOS-based devices from 6S onwards suffer from hardware 48khz lock, rendering them unable to play old 22khz RjDj scenes properly

**Comment by danomatika** [comment]
I haven’t had any time to revisit this beyond starting a new branch using an AVAudioConverter which is not working yet.

enohp ym morf tnes
-----------
Dan Wilcox
danomatika.com
robotcowboy.com

**Comment by danomatika** [comment]
Also, the devices I have around to test all have headphone jacks, so I've not run into this problem first hand. I can only partially test using the simulator and changing the system samplerate.

**Comment by fomalsd** [comment]
Hit me up if you need to test something on hardware without a jack. I assume you were referring to `buffered-audiounit2` branch and #228 PR?

Also this might be a premature question, but any idea if low sample rate patches would still retain any latency/processing speed benefit over native rate after conversion?

P.S. 6S does have an audio jack (they were gone on iPhones since the 7) but is (reportedly) still fixed at 48khz, I assume it's also the case for recent non-Pro iPads that still have the jack

**Comment by cerupcat** [comment]
Not 100% sure I understand the issue you're running into @fomalsd, but on iOS I'm using https://github.com/TheAmazingAudioEngine/TheAmazingAudioEngine as the audio manager instead of the libpd iOS code and don't have any issues (other than some reports of airpods). With that said, I'm also not using any rjdj patches, so I don't know if what you're experiencing would still occur.

Overview using TheAmazingAudioEngine:

```

#import "AudioService.h"
#import <TheAmazingAudioEngine/TheAmazingAudioEngine.h>
#include <AudioToolbox/AudioToolbox.h>
#include <AVFoundation/AVFoundation.h>
#import <libpd/PdBase.h>
#import <libpd/PdDispatcher.h>
#import <libpd/PdFile.h>
#import <Accelerate/Accelerate.h>
#include <mach/mach_time.h>
#import "AEUtilities.h"

@interface AudioService() {
    float * inBuffer;
    int samplerate;
    int buffersize;
    int inChannels;
    int outChannels;
    UInt32 outputLatency;
    UInt32 tickTime;
    bool isReconfiguring;
}

@property (nonatomic, strong) AEAudioController *controller;
@property (nonatomic, strong) PdDispatcher *dispatcher;

@end

@implementation AudioService

int log2int(int x) {
    int y = 0;
    while (x >>= 1) {
        ++y;
    }
    return y;
}

+ (AudioService *)sharedInstance
{
    static AudioService* _sharedClient;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sharedClient = [[AudioService alloc] init];
        kPdBlockSize = [PdBase getBlockSize];
        _blockSizeAsLog = log2int([PdBase getBlockSize]);
    });
    return _sharedClient;
}

- (void)setupAudio
{
    [[NSNotificationCenter defaultCenter] addObserver: self
                                             selector: @selector(applicationWillTerminate:)
                                                 name: UIApplicationWillTerminateNotification
                                               object: nil];

    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(audioRouteChanged:)
                                                 name:AVAudioSessionRouteChangeNotification
                                               object:nil];

    // For some reason this needs to be stereo in order for microphone input to work
    AudioStreamBasicDescription stereoFormat = {
        .mSampleRate       = 44100.f,
        .mFormatID         = kAudioFormatLinearPCM,
        .mFormatFlags      = kAudioFormatFlagsNativeFloatPacked,
        .mFramesPerPacket  = 1,
        .mChannelsPerFrame = 1,
        .mBytesPerFrame    = sizeof(Float32) * 1,
        .mBytesPerPacket   = sizeof(Float32) * 1,
        .mBitsPerChannel   = sizeof(Float32) * 8
    };

    isReconfiguring = NO;
    inBuffer = NULL;

    AEAudioControllerOptions options = static_cast<AEAudioControllerOptions>(AEAudioControllerOptionEnableInput | AEAudioControllerOptionEnableOutput | AEAudioControllerOptionEnableBluetoothInput | AEAudioControllerOptionAllowMixingWithOtherApps | AEAudioControllerOptionUseHardwareSampleRate);
    self.controller = [[AEAudioController alloc] initWithAudioDescription:stereoFormat options:options];
    self.controller.preferredBufferDuration = .03; // 1024 frames

    [self configureSampleRate:self.controller.audioDescription.mSampleRate inChannels:1 outChannels:1];

    // SETUP TAE
    id<AEAudioReceiver> input = [self setupAudioInput];
    AEBlockChannel *output = [self setupAudioOutput];

    [self.controller addInputReceiver:input];
    [self.controller addChannels:@[output]];
}

- (id<AEAudioReceiver>)setupAudioInput
{
    __typeof(self) __weak weakSelf = self;
    id<AEAudioReceiver> input = [AEBlockAudioReceiver audioReceiverWithBlock:^(void *source,
                                                                                const AudioTimeStamp *time,
                                                                                UInt32 frames,
                                                                                AudioBufferList *audio) {
        __typeof__(self) strongSelf = weakSelf;
        AudioBuffer * audioBuffer = &audio->mBuffers[0];
        if (strongSelf->samplerate == strongSelf.controller.audioDescription.mSampleRate &&
            strongSelf->inChannels == audioBuffer->mNumberChannels &&
            strongSelf->buffersize == frames) {
            if(strongSelf->inBuffer != NULL) {
                memcpy(strongSelf->inBuffer, (float*)audioBuffer->mData, audioBuffer->mDataByteSize);
            }
        } else if (!strongSelf->isReconfiguring) {

            strongSelf->isReconfiguring = YES;

            reconfigureStruct p;
            p.mNumberInChannels = audioBuffer->mNumberChannels;
            p.mNumberOutChannels = self->outChannels;
            p.THIS = strongSelf;

            AEAudioControllerSendAsynchronousMessageToMainThread(strongSelf.controller,
                                                                 reconfigure,
                                                                 &p,
                                                                 sizeof(struct reconfigureStruct));
        }
    }];

    return input;
}

struct reconfigureStruct {
    UInt32 mNumberInChannels;
    UInt32 mNumberOutChannels;
    __unsafe_unretained AudioService * THIS;
};

- (AEBlockChannel*)setupAudioOutput
{
    __typeof(self) __weak weakSelf = self;
    AEBlockChannel *output = [AEBlockChannel channelWithBlock:^(const AudioTimeStamp  *time,
                                                                 UInt32 frames,
                                                                 AudioBufferList *audio) {

        AudioBuffer * audioBuffer = &audio->mBuffers[0];
        memset(audioBuffer->mData, 0, audioBuffer->mDataByteSize);

        // update samplerate
        __typeof__(self) strongSelf = weakSelf;

        if (strongSelf->samplerate == strongSelf.controller.audioDescription.mSampleRate &&
            strongSelf->inChannels == audioBuffer->mNumberChannels &&
            strongSelf->buffersize == frames) {
            Float32 *outBuffer = (Float32 *)audio->mBuffers[0].mData;
            float *inBuff = strongSelf->inBuffer;
            if(inBuff != NULL) {
                // this is a faster way of computing (frame / blockSize)
                int ticks = frames >> _blockSizeAsLog;
                UInt64 hostTimeAfterTick = time->mHostTime + strongSelf->outputLatency;
                int bufSizePerTick = kPdBlockSize * strongSelf->outChannels;
                for (int i = 0; i < ticks; i++) {
                    hostTimeAfterTick += strongSelf->tickTime;
                    [PdBase processFloatWithInputBuffer:inBuff outputBuffer:outBuffer ticks:1];
                    inBuff += bufSizePerTick;
                    outBuffer += bufSizePerTick;
                }
            }
        } else if (!strongSelf->isReconfiguring) {

            strongSelf->isReconfiguring = YES;

            reconfigureStruct p;
            p.mNumberOutChannels = audioBuffer->mNumberChannels;
            p.mNumberInChannels = self->inChannels;
            p.THIS = strongSelf;

            AEAudioControllerSendAsynchronousMessageToMainThread(strongSelf.controller,
                                                                 reconfigure,
                                                                 &p,
                                                                 sizeof(struct reconfigureStruct));
        }
    }];

    return output;
}

- (void)setupPd
{
    // setup externals

    // setup delegate
    self.dispatcher = [[PdDispatcher alloc] init];
    [PdBase setDelegate:self.dispatcher];

    // open patch
    [PdBase openFile:@"MAIN_TUNER.pd" path:[NSBundle mainBundle].resourcePath];
}

static void reconfigure(void *userInfo, int userInfoLength)
{
    struct reconfigureStruct * arg = (struct reconfigureStruct*)userInfo;
    AudioService *THIS = arg->THIS;

    // reconfigure
    [THIS configureSampleRate:THIS.controller.audioDescription.mSampleRate
                   inChannels:arg->mNumberInChannels
                  outChannels:arg->mNumberOutChannels];
}

- (void)configureSampleRate:(int)samplerate_ inChannels:(int)inChannels_ outChannels:(int)outChannels_
{
    [PdBase computeAudio:NO];

    // clear in buffer
    if(self->inBuffer != NULL) {
        delete[] self->inBuffer;
        self->inBuffer = NULL;
    }

    self->samplerate = samplerate_;
    self->inChannels = inChannels_;
    self->outChannels = outChannels_;
    self->buffersize = (int)round([AVAudioSession sharedInstance].IOBufferDuration * self->samplerate);

    mach_timebase_info_data_t timeInfo;
    mach_timebase_info(&timeInfo);
    float secondsToHostTime = (1.0e9 * timeInfo.denom) / (Float64)timeInfo.numer;
    self->outputLatency = (UInt32)(secondsToHostTime * [AVAudioSession sharedInstance].outputLatency);
    self->tickTime = (UInt32)(secondsToHostTime * kPdBlockSize / self->samplerate);

    // allocate buffers
    self->inBuffer = new float[inChannels*buffersize];

    [PdBase openAudioWithSampleRate:self->samplerate inputChannels:self->inChannels outputChannels:self->outChannels];

    [self startAudio];
}

- (void)startAudio
{
    if (self.controller == nil) {
        return;
    }

    NSError *error = NULL;
    BOOL result = [self.controller start:&error];
    if ( !result ) {
        NSLog(@"audio error %@", error);
        return;
    }

    // set initial port
    [self handlePortChange];

    // enable PD
    [PdBase computeAudio:YES];

    // enable link
    ABLLinkSetActive(linkRef, YES);
}

- (void)stopAudio
{
    if (self.controller == nil) {
        return;
    }

    [self.controller stop];
    [PdBase computeAudio:NO];
}

-(void)applicationWillTerminate:(UIApplication *)application
{
    if (self.controller == nil) {
        return;
    }

    [NSObject cancelPreviousPerformRequestsWithTarget: self selector:@selector(startAfterDelay) object: self];
    [[NSNotificationCenter defaultCenter] removeObserver:self];

    [self.controller stop];

    [PdBase computeAudio:NO];
}

- (void)audioRouteChanged:(NSNotification *)notification
{
    if (self.controller == nil) {
        return;
    }

    [self handlePortChange];
}

- (void)handlePortChange
{
    // ensure the current route is outputting from build in speaker
    AVAudioSessionRouteDescription* route = [[AVAudioSession sharedInstance] currentRoute];
    for (AVAudioSessionPortDescription* desc in [route outputs]){
        if ([[desc portType] isEqualToString:AVAudioSessionPortBuiltInReceiver]){
            NSError* error = nil;
            BOOL result = NO;
            result =  [[AVAudioSession sharedInstance] overrideOutputAudioPort:AVAudioSessionPortOverrideSpeaker
                                                                         error:&error];
            if (!result){
                NSLog(@"set override speaker failed");
            }
        }
    }
}
@end
```

**Comment by danomatika** [comment]
@fomalsd @cerupcat Please see PR #283.

@rpattabi If the buffer size is the only issue (ie. Android doesn't provide built in sr conversion and.or you don't need it), then the approach I use in the PR would work in the OpenSSL code. I basically check if the Pd sample rate matches the system sample rate. If not, then the input samples are fed into an input ring buffer. Pd then processes as many blocks as it can and feeds the into an output ring buffer which is then used to feed output samples to the system.

**Comment by cerupcat** [comment]
Thanks @danomatika , i'll have to check it out.

On Android, I've moved to integrating things into Google's Oboe library (https://github.com/google/oboe) since there are too many device-specific issues on Android.

**Comment by rpattabi** [comment]
As @cerupcat mentioned, there are many device-specific issues when pd is used in Android. This issue especially happens for us when there is `adc~` in the patch **with an input channel**, even when not processing input. In this case, simple sine wave playback itself crackles. The same patch (with `adc~`) plays audio without crackle on the same devices when we don't enable input channel.

@danomatika I would love to test if PR #283 addresses this problem. I don't know how to integrate these changes locally to libpd, then update pd-for-android in order to test it with my app on problem device. How should I go about it?

**Comment by danomatika** [comment]
#238 probably doesn't help you as it's changes to Obj-C only. My suggestion was that the OpenSSL JNI code could be changed to use IO ring buffers, if it doesn't already.

If you have channel mismatches, ie. device-provided buffer has only 1 channel while pd expects 2 channel input, then that is more involved and requires some manual sample copying.

**Comment by rpattabi** [comment]
Thanks for the clarification. We're using only one input channel. That too no processing of input during playback. Thus, we assume there won't be channel mismatches, or the need for manual sample copying.

**Comment by rpattabi** [comment]
Linking libpd/libpd#284

**Comment by danomatika** [comment]
Closing due to lack of activity.
